### ISSUE TITLE
hello, the rar is corrupted

### ISSUE THREAD

**Issue by kup235** [neverfail/pt-patcher#1]
hello, i think the rar is corrupted also verison 19, can you upload again please, many thanks.

**Comment by kup235** [comment]
i say this file v1.2.6.20_9842439

**Comment by neverfail** [comment]
Issue is confirmed, the release file is corrupted and the patch applied manually is not enough for latest release. A patch is coming.

**Comment by neverfail** [comment]
After testing more thoroughly, the release version is indeed broken.

```shell
$ unzip ProfitTrailerPatched.zip
Archive:  ProfitTrailerPatched.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ProfitTrailerPatched.zip or
        ProfitTrailerPatched.zip.zip, and cannot find ProfitTrailerPatched.zip.ZIP, period.
```

But the release works fine.

```
2018-02-28 19:30:31 DEBUG Application - {"validLicense":true,"default":"default"}
```

So I will delete latest release and make travis rebuild it.

**Comment by neverfail** [comment]
Automatic builds still fail to do the archive.

**Comment by neverfail** [comment]
And now it's fixed. Enjoy.

**Comment by kup235** [comment]
hello, can you patch this please?
https://github.com/mehtadone/PTFeeder/releases/tag/pt-feeder-v1.4.0.431

thank you

2018-02-28 20:08 GMT+00:00 NeverFail Team <notifications@github.com>:

**Comment by neverfail** [comment]
We do not take requests.  
Please consider making a donation, (link in the end of README) if you want more projects to come.
